<?php
/**
 * @file
 * YouTube module file.
 */

function youtube_block_info() {
  $blocks['youtube_videos_block'] = array(
    'info' => t('YouTube Videos'),
    'cache'=> DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}//end of youtube block info


/**
 * Create a drupal content type with the following fields:
 * - Thumbnail image_src
 * - Updated Date for sorting the image_src
 * - Title
 * - Embed URL

 * So this module reads the Title and Embed URL from your node.

 */

function youtube_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'youtube_videos_block':
      $title="";
      $layout ="";
      $query = new EntityFieldQuery();
      $query->fieldOrderBy('field_updated_date_video', 'value', 'DESC');
      $result = $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'story_video_')
        ->pager(12)
        ->execute();
      $nodes = node_load_multiple(array_keys($result['node']));
      $pager= theme('pager');
      $all_gallery_output="<div class='row'>";
      $row_breaker=0;
      foreach ($nodes as $record) {
        $gallery_link="";
        $title= $record->title;
        $nid=$record->nid;
        $image_src = file_create_url($record->field_youtube_thumbnail['und'][0]['uri']);
        $embeded_url=$record->field_youtube_embed_url['und'][0]['value'];
        $updated_date=date('j F Y',strtotime(($record->field_updated_date_video['und'][0]['value'])));
        $gallery_link=$gallery_link.'<div class="col-md-4 col-sm-6 col-xs-12 margin40-top-bottom news-thumbnail"><span class="img-responsive margin20-bottom" ><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p0" data-tags="Awesome" data-video-url="false"><div href="#lb-gallery1-'.$nid.'" data-slide-to="0" data-toggle="modal"><img src="'.$image_src.'" style="width: 360px; height: 270px;" /><span class="icon-focus"></span></div></div></span><div class="grey" >'.$updated_date.'</div><h3 style="color: #545454;">'.$title.'</h3></div>';
        $get_render_output = youtube_content_builder($nid,$title,$embeded_url);
        $gallery_link=$gallery_link.$get_render_output;
        $all_gallery_output=$all_gallery_output.$gallery_link;
        if(($row_breaker+1)%3==0)
          $all_gallery_output=$all_gallery_output."</div><div class='row'>";
        $row_breaker = $row_breaker+1;
     }
     $all_gallery_output=$all_gallery_output."</div>";
     $block['subject'] = t('YouTube Videos');
     $block['content'] =$all_gallery_output.$pager;
     break;
 }
 return $block;
}//end of YouTube view block method

/**
 * Fetch API data from YouTube.
 *
 *
 */

function youtube_content_builder($nid,$title,$embeded_url){
  return $render_output='
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery1-'.$nid.'" >
      <div class="modal-dialog" style="top: 0%; width: 850px;">
        <div class="modal-content">
          <div class="modal-body">
            <div class="carousel-item"><iframe width="850px" height="500px" src="'.$embeded_url.'"></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>';
  echo $render_output;
}
